SystemDiskSize: 40
RuntimeType: Container
ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: a773516179/TrendRadar
DockerComposeEnvPath: docker/.env
RegionId: cn-hangzhou
CustomParameters: ''
DockerComposeYamlPath: docker/docker-compose.yml
Owner: a773516179
Branch: master
Platform: github
